version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_CUSTOM_LDIF_DIR=/etc/ldif
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - ./org_backup.ldif:/etc/ldif/my_org.ldif
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  liquibase:
    depends_on:
      - postgres
    image: liquibase/liquibase
    volumes:
    - .:/liquibase/changelog
    command: '--url="jdbc:postgresql://postgres:5432/grafana" --changeLogFile=changelog.xml --username=postgres --password=postgres update'
  grafana:
    image: docker.io/bitnami/grafana:7
    ports:
      - '3000:3000'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=bitnami'
    volumes:
      - grafana_data:/opt/bitnami/grafana/data
      - ./grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
      - ./ldap.toml:/etc/grafana/ldap.toml
      - ./infra-dashboards:/etc/grafana/dashboards/infra-dashboards
      - ./other-dashboards:/etc/grafana/dashboards/other-dashboards
      - ./dashboards.yaml:/opt/bitnami/grafana/conf/provisioning/dashboards/dashboards.yaml
    depends_on:
      - openldap
      - postgres
      - liquibase
volumes:
  openldap_data:
    driver: local
  grafana_data:
    driver: local
  postgres_data:
    driver: local

